mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: ggcache_plus
  user: root
  password: 123456
logger_setting:
  level: info
  prefix: GGroupCache
  director: log
  show_line: true
  log_in_console: true
ggroupcache:
  name: GGroupCache
  addr:
    - localhost:10001
    - localhost:10002
    - localhost:10003
  ttl: 30
  clean_up_interval: 1 # minute
etcd:
  address:
    - localhost:2379
    - localhost:22379
    - localhost:32379
  ttl: 5                   # second